# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7cyqMO8WxvAgzp6aWVTJlX57Jd2UkWa
"""

"""
Hit Mechanics & Reliability Analysis
Author: Baldessarini
Description: A tool to analyze the probability, reliability (Sigma), and volatility of
Random Number Generator (RNG) based mechanics in gaming.
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# ==========================================
# CONFIGURATION
# ==========================================
N_TRIALS = 100       # Number of hits per encounter
K_TARGET = 30        # Target number of successes (e.g., crits)
P_EXAMPLE = 0.36      # Your current stat (e.g., 30% crit chance)

def calculate_exact_probability(n, k, p):
    """Prints the exact math for a specific scenario."""
    prob_exact = stats.binom.pmf(k, n, p)
    prob_at_least = stats.binom.sf(k - 1, n, p)

    print(f"\n--- ANALYSIS FOR p={p:.0%} ---")
    print(f"Trials (N): {n}")
    print(f"Target (k): {k}")
    print(f"Chance of EXACTLY {k}: {prob_exact:.2%}")
    print(f"Chance of AT LEAST {k}: {prob_at_least:.2%}")
    print("-" * 35)

def plot_probability_and_sigma(n, k_target):
    """Plots the Probability Curve and Sigma (Reliability) Rating."""
    # Generate p values from 10% to 60%
    p_values = np.linspace(0.1, 0.6, 300)

    # 1. Probability (Survival Function)
    probs = stats.binom.sf(k_target - 1, n, p_values)

    # 2. Sigma (Z-Score)
    # Z = (Mean - Target) / StdDev
    means = n * p_values
    std_devs = np.sqrt(n * p_values * (1 - p_values))
    sigmas = (means - k_target) / std_devs

    # --- PLOTTING ---
    fig, ax1 = plt.subplots(figsize=(12, 7))

    # Left Axis: Probability
    color_prob = '#2c7bb6'
    ax1.set_xlabel('Crit Chance (p)', fontsize=12)
    ax1.set_ylabel('Probability of Success', color=color_prob, fontsize=12)
    ax1.plot(p_values, probs, linewidth=3, color=color_prob, label='Probability')
    ax1.tick_params(axis='y', labelcolor=color_prob)
    ax1.grid(True, alpha=0.3)

    # Right Axis: Sigma
    ax2 = ax1.twinx()
    color_sigma = '#d7191c'
    ax2.set_ylabel('Sigma Rating (Z-Score)', color=color_sigma, fontsize=12)
    ax2.plot(p_values, sigmas, linewidth=2, linestyle='-.', color=color_sigma, label='Sigma Rating')
    ax2.tick_params(axis='y', labelcolor=color_sigma)

    # Focus on the relevant Sigma range (-3 to +5)
    ax2.set_ylim(-3, 5)

    # Threshold Lines
    ax2.axhline(0, color='gray', linestyle=':', alpha=0.5)
    ax2.axhline(2, color='green', linestyle='--')
    ax2.text(0.12, 2.1, '2 Sigma (Reliable)', color='green', fontweight='bold')
    ax2.axhline(3, color='purple', linestyle='--')
    ax2.text(0.12, 3.1, '3 Sigma (Guaranteed)', color='purple', fontweight='bold')

    plt.title(f'Reliability Analysis: Probability vs Sigma (N={n}, Target={k_target})')
    plt.tight_layout()
    plt.show()

def simulate_volatility(n, k_target, p):
    """Simulates 100 fights to demonstrate volatility."""
    n_sims = 100
    rng = np.random.default_rng(42)
    results = rng.binomial(n, p, n_sims)

    plt.figure(figsize=(12, 5))

    # Colors based on success/fail
    colors = ['green' if x >= k_target else 'red' for x in results]
    plt.scatter(range(n_sims), results, c=colors, alpha=0.7)

    plt.axhline(k_target, color='black', linestyle='-', label=f'Target ({k_target})')
    plt.axhline(np.mean(results), color='blue', linestyle='--', label=f'Actual Avg ({np.mean(results):.1f})')

    plt.title(f'Volatility Simulation: 100 Separate Encounters (p={p})')
    plt.xlabel('Encounter Number')
    plt.ylabel('Successful Hits')
    plt.legend()
    plt.show()

if __name__ == "__main__":
    # 1. Text Calculation
    calculate_exact_probability(N_TRIALS, K_TARGET, P_EXAMPLE)

    # 2. Main Graph
    plot_probability_and_sigma(N_TRIALS, K_TARGET)

    # 3. Volatility Check
    simulate_volatility(N_TRIALS, K_TARGET, P_EXAMPLE)
