# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMS-hng78MW2F7UtM5_6PeDQrXUNh-iU
"""

# -*- coding: utf-8 -*-
"""
Hit Mechanics & Reliability Analysis
Author: Baldessarini
Description: A tool to analyze the probability, reliability (Sigma), and volatility of
Random Number Generator (RNG) based mechanics in gaming.
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# ==========================================
# CONFIGURATION
# ==========================================
N_TRIALS = 50       # Number of hits per encounter
K_TARGET = 20        # Target number of successes (for the first graph)
P_EXAMPLE = 0.4      # Your current stat (e.g., 30% crit chance)

def calculate_exact_probability(n, k, p):
    """Prints the exact math for a specific scenario."""
    prob_exact = stats.binom.pmf(k, n, p)
    prob_at_least = stats.binom.sf(k - 1, n, p)

    print(f"\n--- ANALYSIS FOR p={p:.0%} ---")
    print(f"Trials (N): {n}")
    print(f"Target (k): {k}")
    print(f"Chance of EXACTLY {k}: {prob_exact:.2%}")
    print(f"Chance of AT LEAST {k}: {prob_at_least:.2%}")
    print("-" * 35)

def plot_probability_and_sigma(n, k_target):
    """Plots the Probability Curve and Sigma (Reliability) Rating."""
    # Generate p values from 10% to 60%
    p_values = np.linspace(0.1, 0.6, 300)

    # 1. Probability (Survival Function)
    probs = stats.binom.sf(k_target - 1, n, p_values)

    # 2. Sigma (Z-Score)
    # Z = (Mean - Target) / StdDev
    means = n * p_values
    std_devs = np.sqrt(n * p_values * (1 - p_values))
    sigmas = (means - k_target) / std_devs

    # --- PLOTTING ---
    fig, ax1 = plt.subplots(figsize=(12, 7))

    # Left Axis: Probability
    color_prob = '#2c7bb6'
    ax1.set_xlabel('Crit Chance (p)', fontsize=12)
    ax1.set_ylabel('Probability of Success', color=color_prob, fontsize=12)
    ax1.plot(p_values, probs, linewidth=3, color=color_prob, label='Probability')
    ax1.tick_params(axis='y', labelcolor=color_prob)
    ax1.grid(True, alpha=0.3)

    # Right Axis: Sigma
    ax2 = ax1.twinx()
    color_sigma = '#d7191c'
    ax2.set_ylabel('Sigma Rating (Z-Score)', color=color_sigma, fontsize=12)
    ax2.plot(p_values, sigmas, linewidth=2, linestyle='-.', color=color_sigma, label='Sigma Rating')
    ax2.tick_params(axis='y', labelcolor=color_sigma)

    # Focus on the relevant Sigma range (-3 to +5)
    ax2.set_ylim(-3, 5)

    # Threshold Lines
    ax2.axhline(0, color='gray', linestyle=':', alpha=0.5)
    ax2.axhline(2, color='green', linestyle='--')
    ax2.text(0.12, 2.1, '2 Sigma (Reliable)', color='green', fontweight='bold')
    ax2.axhline(3, color='purple', linestyle='--')
    ax2.text(0.12, 3.1, '3 Sigma (Guaranteed)', color='purple', fontweight='bold')

    plt.title(f'Reliability Analysis: Probability vs Sigma (N={n}, Target={k_target})')
    plt.tight_layout()
    plt.show()

def plot_chance_to_beat_mean(n):
    """
    Plots the probability of scoring >= your expected rating.
    This demonstrates the 'Sawtooth' effect of RNG.
    """
    # Range of stats (e.g., 1% to 99% Crit)
    p_values = np.linspace(0.01, 0.99, 1000)

    # Calculate the Target for each p (Expected Value rounded up)
    # If p=0.3 and N=100, Expectation is 30. We check P(X >= 30).
    targets = np.ceil(n * p_values)

    # Probability of hitting at least that target
    probs = stats.binom.sf(targets - 1, n, p_values)

    plt.figure(figsize=(12, 6))

    # Plot the line
    plt.plot(p_values * 100, probs * 100, color='#663399', linewidth=1.5)

    # Add the 50% baseline
    plt.axhline(50, color='red', linestyle='--', alpha=0.5, label='50% Coin Flip')

    plt.title(f'Volatility Check: Chance to Meet or Beat Stat Sheet (N={n})')
    plt.xlabel('Your Stat Rating (%)')
    plt.ylabel('Chance to Score >= Rating (%)')
    plt.legend()
    plt.grid(True, alpha=0.3)

    # Add text to explain the chaos
    plt.figtext(0.5, 0.01,
                "The 'Sawtooth' pattern shows there is no consistent 'sweet spot'.\nYou are always hovering near a 50% chance to beat your own average.",
                ha="center", fontsize=10, bbox={"facecolor":"orange", "alpha":0.2, "pad":5})

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    # 1. Text Calculation
    calculate_exact_probability(N_TRIALS, K_TARGET, P_EXAMPLE)

    # 2. Main Graph (Fixed Target)
    plot_probability_and_sigma(N_TRIALS, K_TARGET)

    # 3. Volatility Graph (Variable Target)
    plot_chance_to_beat_mean(N_TRIALS)