# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMS-hng78MW2F7UtM5_6PeDQrXUNh-iU
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_diminishing_returns():
    # --- 1. CONFIGURATION ---
    # Based on your data:
    # Base Damage (0 SP) = 2634
    # Effective Coefficient (Multiplier) = 1.558
    BASE_DMG = 2634
    COEFF = 1.558

    # We simulate a player going from 0 to 3000 Spell Power
    current_sp = np.linspace(0, 3000, 100)

    # --- 2. CALCULATIONS ---
    # Total Damage at each SP point
    total_dmg = BASE_DMG + (current_sp * COEFF)

    # The "Diminishing Return" calculation:
    # If we add +100 SP (e.g., a new item), what % increase is that?
    added_sp = 100
    new_dmg_with_upgrade = BASE_DMG + ((current_sp + added_sp) * COEFF)

    # % Increase = (New / Old) - 1
    percent_gain = ((new_dmg_with_upgrade / total_dmg) - 1) * 100

    # --- 3. PLOTTING ---
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

    # Plot 1: The Reality (Linear)
    ax1.plot(current_sp, total_dmg, color='#1f77b4', linewidth=2)
    ax1.set_title("Absolute Effect: Total Damage vs Spell Power", fontweight='bold')
    ax1.set_ylabel("Damage per Cast")
    ax1.set_xlabel("Current Spell Power")
    ax1.grid(True, alpha=0.3)
    ax1.annotate('Always a straight line\n(No diminishing returns on raw damage)',
                 xy=(1500, 5000), xytext=(200, 6000),
                 arrowprops=dict(facecolor='black', shrink=0.05))

    # Plot 2: The Perception (Diminishing)
    ax2.plot(current_sp, percent_gain, color='#d62728', linewidth=2)
    ax2.set_title("Relative Value: % DPS Gain from adding +100 SP", fontweight='bold')
    ax2.set_ylabel("% DPS Increase")
    ax2.set_xlabel("Current Spell Power")
    ax2.grid(True, alpha=0.3)

    # Mark the user's current spot (1624 SP)
    user_sp = 1624
    user_dps_gain = ((BASE_DMG + (user_sp + 100)*COEFF) / (BASE_DMG + user_sp*COEFF) - 1) * 100

    ax2.plot(user_sp, user_dps_gain, 'ro') # Red dot
    ax2.annotate(f'You are here (1624 SP)\n+100 SP gives {user_dps_gain:.2f}% gain',
                 xy=(user_sp, user_dps_gain), xytext=(user_sp+200, user_dps_gain+1),
                 arrowprops=dict(facecolor='black', shrink=0.05))

    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    plot_diminishing_returns()