# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMS-hng78MW2F7UtM5_6PeDQrXUNh-iU
"""

import matplotlib.pyplot as plt
import numpy as np

# --- Configuration ---
HASTE_RATING_PER_PERCENT = 15.77
MAX_RATING = 1000   # Cap at 1000 rating
TIME_WINDOW = 100   # 100 seconds window for throughput calculation

# Base Cast Times
cast_time_long = 2.5
cast_time_short = 1.5

# --- Calculations ---
ratings = np.linspace(0, MAX_RATING, 500)
haste_pct = ratings / HASTE_RATING_PER_PERCENT / 100

# 1. Calculate Cast Times (Left Graph Data)
# Formula: Base / (1 + Haste%)
time_long = cast_time_long / (1 + haste_pct)
time_short_raw = cast_time_short / (1 + haste_pct)
# Apply GCD Floor (cannot go below 1.0s)
time_short_capped = np.maximum(1.0, time_short_raw)

# 2. Calculate Throughput / Number of Casts (Right Graph Data)
# Formula: Window / RealCastTime
casts_long = TIME_WINDOW / time_long
casts_short = TIME_WINDOW / time_short_capped

# --- Plotting ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# === GRAPH 1: Cast Time Reduction (The Curve) ===
ax1.plot(ratings, time_long, label='2.5s Base Cast', color='#1f77b4', linewidth=2.5)
ax1.plot(ratings, time_short_capped, label='1.5s Base Cast (GCD)', color='#ff7f0e', linewidth=2.5)

# Formatting Graph 1
ax1.set_title('Graph A: Reduction in Cast Time\n(Shows "Diminishing" Returns on Time)', fontsize=14)
ax1.set_xlabel('Haste Rating', fontsize=12)
ax1.set_ylabel('Cast Time (Seconds)', fontsize=12)
ax1.grid(True, which='both', linestyle='--', alpha=0.5)
ax1.axhline(y=1.0, color='red', linestyle='--', alpha=0.5, label='GCD Floor (1.0s)')
ax1.legend()

# === GRAPH 2: Throughput Increase (The Line) ===
ax2.plot(ratings, casts_long, label='2.5s Base Cast', color='#1f77b4', linewidth=2.5)
ax2.plot(ratings, casts_short, label='1.5s Base Cast', color='#ff7f0e', linewidth=2.5)

# Formatting Graph 2
ax2.set_title('Graph B: Total Casts in 100s\n(Shows Linear DPS Gain)', fontsize=14)
ax2.set_xlabel('Haste Rating', fontsize=12)
ax2.set_ylabel('Number of Casts', fontsize=12)
ax2.grid(True, which='both', linestyle='--', alpha=0.5)

# Annotate the GCD Cap on Graph 2
cap_rating = 50 * HASTE_RATING_PER_PERCENT # ~788
if cap_rating < MAX_RATING:
    ax2.axvline(x=cap_rating, color='red', linestyle=':', alpha=0.8)
    ax2.text(cap_rating + 20, casts_short[0] + 5, 'GCD Hard Cap (~788)', color='red', fontsize=10)

plt.tight_layout()
plt.show()